# Exemplos de consultas
# 

# Cargos em disputa em Feira de Santana, BA
http://divulgacandcontas.tse.jus.br/divulga/rest/v1/eleicao/listar/municipios/2030402020/35157/cargos
###

# Candidatos a prefeito em Feira de Santana, BA
http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/listar/2020/35157/2030402020/11/candidatos
###
